### ISSUE TITLE
ModuleNotFoundError: No module named 'DISTS_pytorch'

### ISSUE THREAD

**Issue by msk7131** [NamecantbeNULL/SRUDC#1]
run python test.py ,then folllowing  error occur:
File "test.py", line 12, in <module>
    from DISTS_pytorch import DISTS
ModuleNotFoundError: No module named 'DISTS_pytorch'

**Comment by NamecantbeNULL** [comment]
Simply enter the following into your terminal and it will install the DISTS module:

```sh
pip install DISTS-pytorch
```
